#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -n "$CONNECTION_TOKEN_FILE" ]]; then
    CODE_ARGS="${CODE_ARGS} --connection-token-file ${CONNECTION_TOKEN_FILE}"
    echo "Using connection secret from ${CONNECTION_TOKEN_FILE}"
elif [[ -n "$CONNECTION_TOKEN" ]]; then
    CODE_ARGS="${CODE_ARGS} --connection-token ${CONNECTION_TOKEN}"
    echo "Using connection token ${CONNECTION_TOKEN}"
else
    CODE_ARGS="${CODE_ARGS} --without-connection-token"
    echo "**** No connection token is set ****"
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 8000" \
        cd /app/vscodium-web s6-setuidgid abc \
            /app/vscodium-web/bin/codium-server \
                --host 0.0.0.0 \
                --port 8000 \
                ${CODE_ARGS}
